### ISSUE TITLE
Pager numbers not advancing beyond 4

### ISSUE THREAD

**Issue by billhennessy** [onweru/hugo-swift-theme#58] opened 2020-02-15 17:57 UTC
Assumes more than 4 pages 
REPRO:
- Click 4 in pager
- Click > button
EXPECTED:
- Numbered bubbles advance to 2-5
ACTUAL:
- Numbered bubbles remain 1-4 (but the page content does advance)

**Comment by onweru** [comment] 2020-02-15 21:57
@billhennessy,

Thanks, will fix.

**Comment by thinkerou** [comment] 2020-02-24 12:15
same issue, thanks!

**Comment by onweru** [comment] 2020-02-25 10:15
@billhennessy, @thinkerou this is now fixed. Let me know if everything works alright. Will close in a couple of days.

**Comment by thinkerou** [comment] 2020-02-25 14:40
@onweru thanks a lot!
![image](https://user-images.githubusercontent.com/4488261/75257310-bf018600-581f-11ea-9958-f114ae2aa721.png)
![image](https://user-images.githubusercontent.com/4488261/75257359-cde83880-581f-11ea-9486-fadf4943a941.png)

**Comment by onweru** [comment] 2020-02-25 15:21
@thinkerou ,

You're most welcome. The ellipsis is a feature and not a bug. I'm using [hugo's internal pagination template](https://github.com/onweru/hugo-swift-theme/blob/93d802d114a4615f0f4c6b3ec5f01470058ed7a3/layouts/partials/archive.html#L14). The ellipsis I believe is used limit the number of pagination links for design (real estate) purposes, which is especially useful on mobile.

<img width="637" alt="Screen Shot 2020-02-25 at 6 18 11 PM" src="https://user-images.githubusercontent.com/16350351/75261132-a7b0a180-57fb-11ea-9ee3-b440936a9eaa.png">

**Comment by billhennessy** [comment] 2020-02-25 18:27
Awesome. Thank you. Looks great.

On February 25, 2020 at 9:22:01 AM, one (notifications@github.com) wrote:

@thinkerou <https://github.com/thinkerou> ,

You're most welcome. The ellipsis is a feature and not a bug. I'm using hugo's
internal pagination template
<https://github.com/onweru/hugo-swift-theme/blob/93d802d114a4615f0f4c6b3ec5f01470058ed7a3/layouts/partials/archive.html#L14>.
The ellipsis I believe is used limit the number of pagination links for
design (real estate) purposes, which is especially useful on mobile.

[image: Screen Shot 2020-02-25 at 6 18 11 PM]
<https://user-images.githubusercontent.com/16350351/75261132-a7b0a180-57fb-11ea-9ee3-b440936a9eaa.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/onweru/hugo-swift-theme/issues/58?email_source=notifications&email_token=AAJHIJAYEHWHONCDVBN4RYLREUZRRA5CNFSM4KV2ZICKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM4LWAI#issuecomment-590920449>,
or unsubscribe

**Closed** 2020-02-25 20:50 UTC
Labels: solved

**Comment by thinkerou** [comment] 2020-03-16 10:38
@onweru thanks a lot!
use 

![image](https://user-images.githubusercontent.com/4488261/76748192-499d2b80-67b5-11ea-8411-c176c1dd3f43.png)

instead of

![image](https://user-images.githubusercontent.com/4488261/76748226-591c7480-67b5-11ea-8edf-88ccc6589a3d.png)

do you think?

**Comment by onweru** [comment] 2020-03-16 14:26
@thinkerou, excellent idea. Will implement
